name: "Disclaim academia.edu articles"

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Puppeteer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:24.4.0
      options: "--privileged --user root"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: "apt update -y && apt install -y sudo"
      - run: "chown -R pptruser ."
      - name: Disclaim academia.edu Articles
        run: sudo -u pptruser bash disclaim
