name: "Disclaim academia.edu articles"

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run puppeteer
        uses: tj-actions/docker-run@v2
        with:
          image: ghcr.io/puppeteer/puppeteer:24.4.0
          name: puppeteer-chrome
          options: '-i --init --cap-add=SYS_ADMIN -v ${{ github.workspace }}:${{ github.workspace }}'
          args: |
            bash -c set -x;export PATH=$PATH:node_modules/.bin; cp -vf ${{ github.workspace }}/* /home/pptruser; npm install; node actions.js'
