name: "Disclaim academia.edu articles"

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Puppeteer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:24.4.0
      options: "--privileged --user root"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: "chown -R pptruser ."
      - name: Install Dependencies
        run: su pptruser '/usr/bin/npm install'
      - name: Disclaim academia.edu Articles
        run: su pptruser '/usr/bin/node actions.js'
