name: "Disclaim academia.edu articles"

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Puppeteer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:24.4.0
      options: "--privileged"

    steps:
      - run: whoami
      - run: env
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Disclaim academia.edu Articles
        run: node actions.js
