name: "Disclaim academia.edu articles"

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - name: Run puppeteer
        uses: tj-actions/docker-run@v2
        with:
          image: ghcr.io/puppeteer/puppeteer:21.3.8
          name: puppeteer-chrome
          options: '-i --init --cap-add=SYS_ADMIN -v ${{ github.workspace }}:${{ github.workspace }}'
          args: |
            bash -c 'npm install && node actions.js'
